### ISSUE TITLE
Tempo2 update to deal with >50 efac/equad parameters in IPTA DR3 dataset

### ISSUE THREAD

**Issue by NihanPol** [conda-forge/tempo2-feedstock#34]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

There was a bug discovered in tempo2 that prevented it from handling PSR J1713 in IPTA DR3 dataset, since it had more than 50 efac and equad parameters, which in turn prevented tempo2 from doing a complete post-noise fit for the timing model.

This issue was fixed yesterday in pull request 88 in the tempo2 bitbucket repo.

This issue is to request an update to the conda build of tempo2 to reflect that change. There is no version bump in tempo2 associated with this change yet, but I have reached out to Kuo Liu to see if that would be possible.

https://bitbucket.org/psrsoft/tempo2/pull-requests/88 

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

**Comment by SixByNine** [comment]
I can definitely increment the version number - just did a very quick patch
today.

I'll try to remember to do it on Monday, but please reach out to me
directly (e.g. IPTA slack) if I forget!

**Comment by SixByNine** [comment]
Tempo2 version has been incremented to 2024.12.1

**Comment by demorest** [comment]
Thanks Mike. I've started up the new conda build (in PR #35 )

**Comment by demorest** [comment]
The linux package has been updated (PR #35 ) but the Mac build failed, so we've skipped it for now.  Will close this and open a new issue to track the Mac problems.
